//This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number 
//generated by the computer. There are also several ways to alter the game, like adding more rounds or 
//displaying the score. It’s quite simple and uses the random function to generate a number.

import inquirer from "inquirer";

let user = await inquirer.prompt({
    name: 'num1',
    type:'list',
    message:'enter number',
    choices:["0","1","2","3","4"]
}
)
let gennum= user.num1;
if (gennum==2){
    console.log("congratulation you are added with two more rounds")
}
else{
    console.log("oh! sorry you lose")
}